services:
  - type: web
    name: be-nest
    env: node
    region: singapore
    plan: free

    buildCommand: |
      npm install
      npm install -g @nestjs/cli
      npm run build

    startCommand: node dist/main.js

    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: development
